name: CI

on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
      steps:
        - name: Download from Google Drive
          uses: satackey/action-google-drive@v1
          with:
            skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
            download-from: /path/to/download
            download-to: ./

            # For those who set up Google Drive API client ID and secret themselves
            google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
            google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        - name: run
          run: ls ./
